# Generated by Django 5.1.6 on 2025-07-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
    ]
