# Generated by Django 5.1.6 on 2025-07-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='images',
            new_name='image',
        ),
    ]
