# Generated by Django 5.1.6 on 2025-07-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_latestblog_alter_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
