# Generated by Django 5.1.6 on 2025-07-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='area',
            field=models.CharField(choices=[('yer', 'yer'), ('daraxt', 'daraxt')], default=False, max_length=50),
        ),
    ]
