# Generated by Django 5.1.6 on 2025-07-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
